# <center> MATH&ML-1. Линейная алгебра в контексте линейных методов. Часть I
---

### 2. Основные понятия линейной алгебры: векторы и действия над ними

In [1]:
import numpy as np

s = np.array([33, 65, 50, 45])
s
## array([33, 65, 50, 45])

array([33, 65, 50, 45])

In [2]:
s[2]
## 50

50

In [3]:
len(s)
## 4

4

In [6]:
# Задание 2.1
# Дан вектор в Python вида 
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
# содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. 
# Будем считать, что температура в январе — t0, то есть отсчёт индексов идёт с нуля.
print(t[5]==28)
print(t[0]==min(t))
print(t[1]==17)
print(t[6]==max(t))

True
True
False
True


##### *ГЕОМЕТРИЧЕСКАЯ ИНТЕРПРЕТАЦИЯ ВЕКТОРА. ВЕКТОРНОЕ ПРОСТРАНСТВО

In [20]:
# Задание 2.2
# Задан вектор 
a = np.array([3, -5])
print(a[0]**2 + a[1]**2)
print(abs(np.arctan(a[1]/a[0]) * 180 / 3.14))

34
59.06618750776313


##### БАЗОВЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ

Сложение/вычитание векторов

In [22]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
## array([15, 23, 14,  8])
print(a - b)
## array([ 5, -7, -4, -6])

[15 23 14  8]
[ 5 -7 -4 -6]


Умножение вектора на скаляр

In [23]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

In [25]:
# Задание 2.5
# Ниже представлены доходы семьи за три месяца
# Доходы мужа: 120, 150 и 190 тысяч рублей
# Доходы жены: 130, 130 и 130 тысяч рублей
# Доходы тёщи: 2, 3 и 2.5 тысячи евро
# курс евро составляет 72 рубля
h = np.array([120, 150, 190])
w = np.array([130, 130, 130])
mil = np.array([2, 3, 2.5])
er = 72
print(mil * er)
print(h + w + mil*er)

[144. 216. 180.]
[394. 496. 500.]


##### *ГЕОМЕТРИЧЕСКАЯ ИНТЕРПРЕТАЦИЯ БАЗОВЫХ ОПЕРАЦИЙ С ВЕКТОРАМИ

In [28]:
# Задание 2.6
# Найдите длину диагонали параллелограмма (сумму векторов), построенного на векторах 
a = np.array([4, 6])
# и 
b = np.array([-1, -2])
np.sqrt((a + b)[0]**2 + (a + b)[1]**2)

5.0

ЛИНЕЙНАЯ КОМБИНАЦИЯ ВЕКТОРОВ

In [29]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u
## array([1800, 3000, 2700])

array([1800, 3000, 2700])

Линейная (не)зависимость

In [30]:
# Задание 2.7
# Найдите линейную комбинацию векторов 
x = np.array([4, 5])
y = np.array([2, 1])
u = np.array([1, 0])
# с коэффициентами 2, -3 и 5 соответственно.
2*x + (-3)*y + 5*u

array([7, 7])

In [31]:
# Задание 2.8
# Юный предприниматель Вовочка мастерит двигатели на водном топливе и продаёт их. 
# За четыре недели он смастерил 3, 4, 5 и 9 двигателей, а продал 1, 5, 3 и 6 двигателей соответственно.
# На изготовление одного двигателя Вовочка тратит 200 рублей, а продаёт двигатели по 400 рублейза штуку.
# Найдите вектор прибыли (разницу между выручкой и затратами) Вовочки за эти четыре недели.
made = np.array([3, 4, 5, 9])
sold = np.array([1, 5, 3, 6])
400 * sold - 200 * made

array([-200, 1200,  200,  600])

Скалярное произведение векторов

In [32]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

In [33]:
# Задание 2.11
# Найдите скалярное произведение векторов
x = np.array([4, 5, -1])
y = np.array([2, 0, 1])
np.dot(x, y)

7

---
### 3. Практика: векторы

##### ВЕКТОРЫ. ПРАКТИЧЕСКАЯ ЗАДАЧА

In [34]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [38]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [37]:
# Задание 3.3
# Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:
Hut_Paradise_values = Hut_Paradise_DF.values
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [39]:
# Задание 3.4
# Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:
Hut_Paradise_values[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [41]:
# Задание 3.5
# Вычислите вектор нежилой площади. Выберите координаты полученного вектора:
Hut_Paradise_values[:, 1] - Hut_Paradise_values[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [43]:
# Задание 3.6
# Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, 
# в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.
# Найдите продолжительность просмотров в минутах во всех квартирах за две недели.
time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])
Hut_Paradise_values[:, 4] @ time

1348

In [44]:
# Дано три вектора:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [49]:
# Задание 3.7
# Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3. Выберите координаты полученного вектора:
2*v - 3*w

array([-3, 14,  3,  4,  2])

In [50]:
# Задание 3.8
# Будет ли эта комбинация ортогональна вектору u?
(2*v - 3*w) @ u

0

---
### 4. Основные понятия линейной алгебры: матрицы и базовые действия с ними

In [51]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [52]:
A.shape
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

a_23= 1 a_32= 3 a_33= 1


---
### 5. Практика: базовые действия над матрицами

In [53]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [78]:
# Задание 5.1
# Составьте матрицу  доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
for i in range(len(Inc)):
    for j in range(len(Inc[i])):
        if i==j:
            print(Inc[i,j])

100
200
100


In [79]:
# Задание 5.2
# Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.
Cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
for i in range(len(Cons)):
    for j in range(len(Cons[i])):
        if i==j:
            print(Cons[i,j])

50
80
140


In [84]:
# Задание 5.3
# Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.
# Используйте полученную ранее матрицу Inc, где доходы расположены по столбцам.
(Inc * (1-0.13))[0]

array([ 87. , 130.5,  78.3])

In [85]:
# Задание 5.4
# Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).
P = Inc * (1-0.13) - Cons
P[2]

array([ 61.8, -26.9, -53. ])

---
### 6. Матричное умножение

##### ПРОИЗВЕДЕНИЕ ДВУХ МАТРИЦ

In [86]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [87]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [88]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [89]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [90]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

---
### 7. Практика: матричное умножение

In [99]:
# Задание 7.1
# Даны матрица A и вектор х:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
# Найдите произведение матрицы A и вектора х в том порядке, в котором их можно умножить
A @ x

array([26, 30])

In [100]:
# Задание 7.2
# Даны две матрицы:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
# Найдите произведение матриц A и B в том порядке, в котором их можно умножить
B @ A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [102]:
# Задание 7.3
# Дана система векторов:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
# Составьте матрицу A, расположив векторы x, y, z в строках. Найдите матрицу Грама G (матрицу скалярных произведений столбцов матрицы ) системы векторов x, y, z
# Чему равна полученная матрица Грама ?
A = np.array([x, y, z])
A.T @ A

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [103]:
# Условие для заданий 7.4 и 7.5
# В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 
# Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.
# В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
# В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [130]:
# Задание 7.4
# Найдите вектор дохода салона по стилистам, если за каждую услугу стилисты платят салону определённую «комиссию».
# Вектор комиссий: 
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
# Выберите координаты вектора прибыли салона:
P = Price_DF.values
C = Count_DF.values
P * C @ com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [131]:
# Задание 7.5
# Найдите вектор дохода стилистов
P * C @ (np.ones(5) - com)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

---
### 8. Обратная матрица. Определитель матрицы